INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng TMCP Công thương Việt Nam', N'ICB', N'VietinBank', N'ICB.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng TMCP Ngoại Thương Việt Nam', N'VCB', N'Vietcombank', N'VCB.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng TMCP Đầu tư và Phát triển Việt Nam', N'BIDV', N'BIDV', N'BIDV.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng Nông nghiệp và Phát triển Nông thôn Việt Nam', N'VBA', N'Agribank', N'VBA.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng TMCP Phương Đông', N'OCB', N'OCB', N'OCB.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng TMCP Quân đội', N'MB', N'MBBank', N'MB.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng TMCP Kỹ thương Việt Nam', N'TCB', N'Techcombank', N'TCB.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng TMCP Á Châu', N'ACB', N'ACB', N'ACB.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng TMCP Việt Nam Thịnh Vượng', N'VPB', N'VPBank', N'VPB.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng TMCP Tiên Phong', N'TPB', N'TPBank', N'TPB.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng TMCP Sài Gòn Thương Tín', N'STB', N'Sacombank', N'STB.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng TMCP Phát triển Thành phố Hồ Chí Minh', N'HDB', N'HDBank', N'HDB.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng TMCP Bản Việt', N'VCCB', N'VietCapitalBank', N'VCCB.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng TMCP Sài Gòn', N'SCB', N'SCB', N'SCB.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng TMCP Quốc tế Việt Nam', N'VIB', N'VIB', N'VIB.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng TMCP Sài Gòn - Hà Nội', N'SHB', N'SHB', N'SHB.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng TMCP Xuất Nhập khẩu Việt Nam', N'EIB', N'Eximbank', N'EIB.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng TMCP Hàng Hải', N'MSB', N'MSB', N'MSB.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'TMCP Việt Nam Thịnh Vượng - Ngân hàng số CAKE by VPBank', N'CAKE', N'CAKE', N'CAKE.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'TMCP Việt Nam Thịnh Vượng - Ngân hàng số Ubank by VPBank', N'Ubank', N'Ubank', N'UBANK.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng số Timo by Ban Viet Bank (Timo by Ban Viet Bank)', N'TIMO', N'Timo', N'TIMO.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Tổng Công ty Dịch vụ số Viettel - Chi nhánh tập đoàn công nghiệp viễn thông Quân Đội', N'VTLMONEY', N'ViettelMoney', N'VIETTELMONEY.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'VNPT Money', N'VNPTMONEY', N'VNPTMoney', N'VNPTMONEY.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng TMCP Sài Gòn Công Thương', N'SGICB', N'SaigonBank', N'SGICB.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng TMCP Bắc Á', N'BAB', N'BacABank', N'BAB.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng TMCP Đại Chúng Việt Nam', N'PVCB', N'PVcomBank', N'PVCB.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng Thương mại TNHH MTV Đại Dương', N'Oceanbank', N'Oceanbank', N'OCEANBANK.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng TMCP Quốc Dân', N'NCB', N'NCB', N'NCB.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng TNHH MTV Shinhan Việt Nam', N'SHBVN', N'ShinhanBank', N'SHBVN.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng TMCP An Bình', N'ABB', N'ABBANK', N'ABB.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng TMCP Việt Á', N'VAB', N'VietABank', N'VAB.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng TMCP Nam Á', N'NAB', N'NamABank', N'NAB.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng TMCP Xăng dầu Petrolimex', N'PGB', N'PGBank', N'PGB.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng TMCP Việt Nam Thương Tín', N'VIETBANK', N'VietBank', N'VIETBANK.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng TMCP Bảo Việt', N'BVB', N'BaoVietBank', N'BVB.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng TMCP Đông Nam Á', N'SEAB', N'SeABank', N'SEAB.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng Hợp tác xã Việt Nam', N'COOPBANK', N'COOPBANK', N'COOPBANK.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng TMCP Lộc Phát Việt Nam', N'LPB', N'LPBank', N'LPB.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng TMCP Kiên Long', N'KLB', N'KienLongBank', N'KLB.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng Đại chúng TNHH Kasikornbank', N'KBank', N'KBank', N'KBANK.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng Kookmin - Chi nhánh Hà Nội', N'KBHN', N'KookminHN', N'KBHN.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng KEB Hana – Chi nhánh Thành phố Hồ Chí Minh', N'KEBHANAHCM', N'KEBHanaHCM', N'KEBHANAHCM.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng KEB Hana – Chi nhánh Hà Nội', N'KEBHANAHN', N'KEBHANAHN', N'KEBHANAHN.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Công ty Tài chính TNHH MTV Mirae Asset (Việt Nam) ', N'MAFC', N'MAFC', N'MAFC.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng Citibank, N.A. - Chi nhánh Hà Nội', N'CITIBANK', N'Citibank', N'CITIBANK.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng Kookmin - Chi nhánh Thành phố Hồ Chí Minh', N'KBHCM', N'KookminHCM', N'KBHCM.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng Chính sách Xã hội', N'VBSP', N'VBSP', N'VBSP.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng TNHH MTV Woori Việt Nam', N'WVN', N'Woori', N'WVN.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng Liên doanh Việt - Nga', N'VRB', N'VRB', N'VRB.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng United Overseas - Chi nhánh TP. Hồ Chí Minh', N'UOB', N'UnitedOverseas', N'UOB.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng TNHH MTV Standard Chartered Bank Việt Nam', N'SCVN', N'StandardChartered', N'SCVN.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng TNHH MTV Public Việt Nam', N'PBVN', N'PublicBank', N'PBVN.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng Nonghyup - Chi nhánh Hà Nội', N'NHB HN', N'Nonghyup', N'NHB.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng TNHH Indovina', N'IVB', N'IndovinaBank', N'IVB.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng Công nghiệp Hàn Quốc - Chi nhánh TP. Hồ Chí Minh', N'IBK - HCM', N'IBKHCM', N'IBK.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng Công nghiệp Hàn Quốc - Chi nhánh Hà Nội', N'IBK - HN', N'IBKHN', N'IBK.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng TNHH MTV HSBC (Việt Nam)', N'HSBC', N'HSBC', N'HSBC.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng TNHH MTV Hong Leong Việt Nam', N'HLBVN', N'HongLeong', N'HLBVN.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng Thương mại TNHH MTV Dầu Khí Toàn Cầu', N'GPB', N'GPBank', N'GPB.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng TMCP Đông Á', N'DOB', N'DongABank', N'DOB.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'DBS Bank Ltd - Chi nhánh Thành phố Hồ Chí Minh', N'DBS', N'DBSBank', N'DBS.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng TNHH MTV CIMB Việt Nam', N'CIMB', N'CIMB', N'CIMB.png');
INSERT INTO bank (name, code, short_name, logo) VALUES (N'Ngân hàng Thương mại TNHH MTV Xây dựng Việt Nam', N'CBB', N'CBBank', N'CBB.png');
