INSERT INTO categories VALUES (N'Thời Trang Nam', null);
INSERT INTO categories VALUES (N'Áo Khoác', 1);
INSERT INTO categories VALUES (N'Áo Vest và Blazer', 1);
INSERT INTO categories VALUES (N'Áo Hoodie, Áo Len & Áo Nỉ', 1);
INSERT INTO categories VALUES (N'Quần Jeans', 1);
INSERT INTO categories VALUES (N'Quần Dài/Quần Âu', 1);
INSERT INTO categories VALUES (N'Quần Short', 1);
INSERT INTO categories VALUES (N'Áo', 1);
INSERT INTO categories VALUES (N'Áo Ba Lỗ', 1);
INSERT INTO categories VALUES (N'Đồ Lót', 1);
INSERT INTO categories VALUES (N'Đồ Ngủ', 1);
INSERT INTO categories VALUES (N'Đồ Bộ', 1);
INSERT INTO categories VALUES (N'Vớ/Tất', 1);
INSERT INTO categories VALUES (N'Trang Phục Truyền Thống', 1);
INSERT INTO categories VALUES (N'Đồ Hóa Trang', 1);
INSERT INTO categories VALUES (N'Trang Phục Ngành Nghề', 1);
INSERT INTO categories VALUES (N'Khác', 1);
INSERT INTO categories VALUES (N'Trang Sức Nam', 1);
INSERT INTO categories VALUES (N'Kính Mắt Nam', 1);
INSERT INTO categories VALUES (N'Thắt Lưng Nam', 1);
INSERT INTO categories VALUES (N'Cà vạt & Nơ cổ', 1);
INSERT INTO categories VALUES (N'Phụ Kiện Nam', 1);
INSERT INTO categories VALUES (N'Nhà Cửa & Đời Sống', null);
INSERT INTO categories VALUES (N'Chăn, Ga, Gối & Nệm', 23);
INSERT INTO categories VALUES (N'Đồ nội thất', 23);
INSERT INTO categories VALUES (N'Trang trí nhà cửa', 23);
INSERT INTO categories VALUES (N'Dụng cụ & Thiết bị tiện ích', 23);
INSERT INTO categories VALUES (N'Đồ dùng nhà bếp và hộp đựng thực phẩm', 23);
INSERT INTO categories VALUES (N'Đèn', 23);
INSERT INTO categories VALUES (N'Ngoài trời & Sân vườn', 23);
INSERT INTO categories VALUES (N'Đồ dùng phòng tắm', 23);
INSERT INTO categories VALUES (N'Vật phẩm thờ cúng', 23);
INSERT INTO categories VALUES (N'Đồ trang trí tiệc', 23);
INSERT INTO categories VALUES (N'Chăm sóc nhà cửa và giặt ủi', 23);
INSERT INTO categories VALUES (N'Sắp xếp nhà cửa', 23);
INSERT INTO categories VALUES (N'Dụng cụ pha chế', 23);
INSERT INTO categories VALUES (N'Tinh dầu thơm phòng', 23);
INSERT INTO categories VALUES (N'Đồ dùng phòng ăn', 23);
INSERT INTO categories VALUES (N'Đồng Hồ', null);
INSERT INTO categories VALUES (N'Đồng Hồ Nam', 39);
INSERT INTO categories VALUES (N'Đồng Hồ Nữ', 39);
INSERT INTO categories VALUES (N'Bộ Đồng Hồ & Đồng Hồ Cặp', 39);
INSERT INTO categories VALUES (N'Đồng Hồ Trẻ Em', 39);
INSERT INTO categories VALUES (N'Phụ Kiện Đồng Hồ', 39);
INSERT INTO categories VALUES (N'Khác', 39);
INSERT INTO categories VALUES (N'Phụ Kiện & Trang Sức Nữ', null);
INSERT INTO categories VALUES (N'Nhẫn', 46);
INSERT INTO categories VALUES (N'Bông tai', 46);
INSERT INTO categories VALUES (N'Khăn choàng', 46);
INSERT INTO categories VALUES (N'Găng tay', 46);
INSERT INTO categories VALUES (N'Phụ kiện tóc', 46);
INSERT INTO categories VALUES (N'Vòng tay & Lắc tay', 46);
INSERT INTO categories VALUES (N'Lắc chân', 46);
INSERT INTO categories VALUES (N'Mũ', 46);
INSERT INTO categories VALUES (N'Dây chuyền', 46);
INSERT INTO categories VALUES (N'Kính mắt', 46);
INSERT INTO categories VALUES (N'Kim loại quý', 46);
INSERT INTO categories VALUES (N'Thắt lưng', 46);
INSERT INTO categories VALUES (N'Cà vạt & Nơ cổ', 46);
INSERT INTO categories VALUES (N'Phụ kiện thêm', 46);
INSERT INTO categories VALUES (N'Bộ phụ kiện', 46);
INSERT INTO categories VALUES (N'Khác', 46);
INSERT INTO categories VALUES (N'Vớ/ Tất', 46);
INSERT INTO categories VALUES (N'Ô/Dù', 46);
INSERT INTO categories VALUES (N'Balo & Túi Ví Nam', null);
INSERT INTO categories VALUES (N'Ba Lô Nam', 65);
INSERT INTO categories VALUES (N'Ba Lô Laptop Nam', 65);
INSERT INTO categories VALUES (N'Túi & Cặp Đựng Laptop', 65);
INSERT INTO categories VALUES (N'Túi Chống Sốc Laptop Nam', 65);
INSERT INTO categories VALUES (N'Túi Tote Nam', 65);
INSERT INTO categories VALUES (N'Cặp Xách Công Sở Nam', 65);
INSERT INTO categories VALUES (N'Ví Cầm Tay Nam', 65);
INSERT INTO categories VALUES (N'Túi Đeo Hông & Túi Đeo Ngực Nam', 65);
INSERT INTO categories VALUES (N'Túi Đeo Chéo Nam', 65);
INSERT INTO categories VALUES (N'Bóp/Ví Nam', 65);
INSERT INTO categories VALUES (N'Khác', 65);
INSERT INTO categories VALUES (N'Voucher & Dịch Vụ', null);
INSERT INTO categories VALUES (N'Nhà hàng & Ăn uống', 77);
INSERT INTO categories VALUES (N'Sự kiện & Giải trí', 77);
INSERT INTO categories VALUES (N'Nạp tiền tài khoản', 77);
INSERT INTO categories VALUES (N'Sức khỏe & Làm đẹp', 77);
INSERT INTO categories VALUES (N'Gọi xe', 77);
INSERT INTO categories VALUES (N'Khóa học', 77);
INSERT INTO categories VALUES (N'Du lịch & Khách sạn', 77);
INSERT INTO categories VALUES (N'Mua sắm', 77);
INSERT INTO categories VALUES (N'Mã quà tặng Shopee', 77);
INSERT INTO categories VALUES (N'Thanh toán hóa đơn', 77);
INSERT INTO categories VALUES (N'Dịch vụ khác', 77);
INSERT INTO categories VALUES (N'Thời Trang Nữ', null);
INSERT INTO categories VALUES (N'Quần', 89);
INSERT INTO categories VALUES (N'Quần đùi', 89);
INSERT INTO categories VALUES (N'Chân váy', 89);
INSERT INTO categories VALUES (N'Quần jeans', 89);
INSERT INTO categories VALUES (N'Đầm/Váy', 89);
INSERT INTO categories VALUES (N'Váy cưới', 89);
INSERT INTO categories VALUES (N'Đồ liền thân', 89);
INSERT INTO categories VALUES (N'Áo khoác, Áo choàng & Vest', 89);
INSERT INTO categories VALUES (N'Áo len & Cardigan', 89);
INSERT INTO categories VALUES (N'Hoodie và Áo nỉ', 89);
INSERT INTO categories VALUES (N'Bộ', 89);
INSERT INTO categories VALUES (N'Đồ lót', 89);
INSERT INTO categories VALUES (N'Đồ ngủ', 89);
INSERT INTO categories VALUES (N'Áo', 89);
INSERT INTO categories VALUES (N'Đồ tập', 89);
INSERT INTO categories VALUES (N'Đồ Bầu', 89);
INSERT INTO categories VALUES (N'Đồ truyền thống', 89);
INSERT INTO categories VALUES (N'Đồ hóa trang', 89);
INSERT INTO categories VALUES (N'Vải', 89);
INSERT INTO categories VALUES (N'Vớ/ Tất', 89);
INSERT INTO categories VALUES (N'Khác', 89);
INSERT INTO categories VALUES (N'Máy Tính & Laptop', null);
INSERT INTO categories VALUES (N'Máy Tính Bàn', 111);
INSERT INTO categories VALUES (N'Màn Hình', 111);
INSERT INTO categories VALUES (N'Linh Kiện Máy Tính', 111);
INSERT INTO categories VALUES (N'Thiết Bị Lưu Trữ', 111);
INSERT INTO categories VALUES (N'Thiết Bị Mạng', 111);
INSERT INTO categories VALUES (N'Máy In, Máy Scan & Máy Chiếu', 111);
INSERT INTO categories VALUES (N'Phụ Kiện Máy Tính', 111);
INSERT INTO categories VALUES (N'Laptop', 111);
INSERT INTO categories VALUES (N'Khác', 111);
INSERT INTO categories VALUES (N'Gaming', 111);
INSERT INTO categories VALUES (N'Giày Dép Nữ', null);
INSERT INTO categories VALUES (N'Bốt', 122);
INSERT INTO categories VALUES (N'Giày Thể Thao/ Sneaker', 122);
INSERT INTO categories VALUES (N'Giày Đế Bằng', 122);
INSERT INTO categories VALUES (N'Giày Cao Gót', 122);
INSERT INTO categories VALUES (N'Giày Đế Xuồng', 122);
INSERT INTO categories VALUES (N'Xăng-đan Và Dép', 122);
INSERT INTO categories VALUES (N'Phụ Kiện Giày', 122);
INSERT INTO categories VALUES (N'Giày Khác', 122);
INSERT INTO categories VALUES (N'Thể Thao & Du Lịch', null);
INSERT INTO categories VALUES (N'Vali', 131);
INSERT INTO categories VALUES (N'Túi du lịch', 131);
INSERT INTO categories VALUES (N'Phụ kiện du lịch', 131);
INSERT INTO categories VALUES (N'Dụng Cụ Thể Thao & Dã Ngoại', 131);
INSERT INTO categories VALUES (N'Giày Thể Thao', 131);
INSERT INTO categories VALUES (N'Thời Trang Thể Thao & Dã Ngoại', 131);
INSERT INTO categories VALUES (N'Phụ Kiện Thể Thao & Dã Ngoại', 131);
INSERT INTO categories VALUES (N'Khác', 131);
INSERT INTO categories VALUES (N'Thời Trang Trẻ Em', null);
INSERT INTO categories VALUES (N'Trang phục bé trai', 140);
INSERT INTO categories VALUES (N'Trang phục bé gái', 140);
INSERT INTO categories VALUES (N'Giày dép bé trai', 140);
INSERT INTO categories VALUES (N'Giày dép bé gái', 140);
INSERT INTO categories VALUES (N'Khác', 140);
INSERT INTO categories VALUES (N'Quần áo em bé', 140);
INSERT INTO categories VALUES (N'Giày tập đi & Tất sơ sinh', 140);
INSERT INTO categories VALUES (N'Phụ kiện trẻ em', 140);
INSERT INTO categories VALUES (N'Dụng cụ và thiết bị tiện ích', null);
INSERT INTO categories VALUES (N'Dụng cụ cầm tay', 149);
INSERT INTO categories VALUES (N'Dụng cụ điện và thiết bị lớn', 149);
INSERT INTO categories VALUES (N'Thiết bị mạch điện', 149);
INSERT INTO categories VALUES (N'Vật liệu xây dựng', 149);
INSERT INTO categories VALUES (N'Thiết bị và phụ kiện xây dựng', 149);
INSERT INTO categories VALUES (N'Điện Thoại & Phụ Kiện', null);
INSERT INTO categories VALUES (N'Điện thoại', 155);
INSERT INTO categories VALUES (N'Máy tính bảng', 155);
INSERT INTO categories VALUES (N'Pin Dự Phòng', 155);
INSERT INTO categories VALUES (N'Pin Gắn Trong, Cáp và Bộ Sạc', 155);
INSERT INTO categories VALUES (N'Ốp lưng, bao da, Miếng dán điện thoại', 155);
INSERT INTO categories VALUES (N'Bảo vệ màn hình', 155);
INSERT INTO categories VALUES (N'Đế giữ điện thoại', 155);
INSERT INTO categories VALUES (N'Thẻ nhớ', 155);
INSERT INTO categories VALUES (N'Sim', 155);
INSERT INTO categories VALUES (N'Phụ kiện khác', 155);
INSERT INTO categories VALUES (N'Thiết bị khác', 155);
INSERT INTO categories VALUES (N'Sắc Đẹp', null);
INSERT INTO categories VALUES (N'Chăm sóc da mặt', 167);
INSERT INTO categories VALUES (N'Tắm & chăm sóc cơ thể', 167);
INSERT INTO categories VALUES (N'Trang điểm', 167);
INSERT INTO categories VALUES (N'Chăm sóc tóc', 167);
INSERT INTO categories VALUES (N'Dụng cụ & Phụ kiện Làm đẹp', 167);
INSERT INTO categories VALUES (N'Vệ sinh răng miệng', 167);
INSERT INTO categories VALUES (N'Nước hoa', 167);
INSERT INTO categories VALUES (N'Chăm sóc nam giới', 167);
INSERT INTO categories VALUES (N'Khác', 167);
INSERT INTO categories VALUES (N'Chăm sóc phụ nữ', 167);
INSERT INTO categories VALUES (N'Bộ sản phẩm làm đẹp', 167);
INSERT INTO categories VALUES (N'Giày Dép Nam', null);
INSERT INTO categories VALUES (N'Bốt', 179);
INSERT INTO categories VALUES (N'Giày Thể Thao/ Sneakers', 179);
INSERT INTO categories VALUES (N'Giày Sục', 179);
INSERT INTO categories VALUES (N'Giày Tây Lười', 179);
INSERT INTO categories VALUES (N'Giày Oxfords & Giày Buộc Dây', 179);
INSERT INTO categories VALUES (N'Xăng-đan và Dép', 179);
INSERT INTO categories VALUES (N'Phụ kiện giày dép', 179);
INSERT INTO categories VALUES (N'Khác', 179);
INSERT INTO categories VALUES (N'Bách Hóa Online', null);
INSERT INTO categories VALUES (N'Đồ ăn vặt', 188);
INSERT INTO categories VALUES (N'Đồ chế biến sẵn', 188);
INSERT INTO categories VALUES (N'Nhu yếu phẩm', 188);
INSERT INTO categories VALUES (N'Nguyên liệu nấu ăn', 188);
INSERT INTO categories VALUES (N'Đồ làm bánh', 188);
INSERT INTO categories VALUES (N'Sữa - trứng', 188);
INSERT INTO categories VALUES (N'Đồ uống', 188);
INSERT INTO categories VALUES (N'Ngũ cốc & mứt', 188);
INSERT INTO categories VALUES (N'Các loại bánh', 188);
INSERT INTO categories VALUES (N'Đồ uống có cồn', 188);
INSERT INTO categories VALUES (N'Bộ quà tặng', 188);
INSERT INTO categories VALUES (N'Thực phẩm tươi sống và thực phẩm đông lạnh', 188);
INSERT INTO categories VALUES (N'Khác', 188);
INSERT INTO categories VALUES (N'Đồ Chơi', null);
INSERT INTO categories VALUES (N'Sở thích & Sưu tầm', 202);
INSERT INTO categories VALUES (N'Đồ chơi giải trí', 202);
INSERT INTO categories VALUES (N'Đồ chơi giáo dục', 202);
INSERT INTO categories VALUES (N'Đồ chơi cho trẻ sơ sinh & trẻ nhỏ', 202);
INSERT INTO categories VALUES (N'Đồ chơi vận động & ngoài trời', 202);
INSERT INTO categories VALUES (N'Búp bê & Đồ chơi nhồi bông', 202);
INSERT INTO categories VALUES (N'Mẹ & Bé', null);
INSERT INTO categories VALUES (N'Đồ dùng du lịch cho bé', 209);
INSERT INTO categories VALUES (N'Đồ dùng ăn dặm cho bé', 209);
INSERT INTO categories VALUES (N'Phụ kiện cho mẹ', 209);
INSERT INTO categories VALUES (N'Chăm sóc sức khỏe mẹ', 209);
INSERT INTO categories VALUES (N'Đồ dùng phòng tắm & Chăm sóc cơ thể bé', 209);
INSERT INTO categories VALUES (N'Đồ dùng phòng ngủ cho bé', 209);
INSERT INTO categories VALUES (N'An toàn cho bé', 209);
INSERT INTO categories VALUES (N'Thực phẩm cho bé', 209);
INSERT INTO categories VALUES (N'Chăm sóc sức khỏe bé', 209);
INSERT INTO categories VALUES (N'Tã & bô em bé', 209);
INSERT INTO categories VALUES (N'Đồ chơi', 209);
INSERT INTO categories VALUES (N'Bộ & Gói quà tặng', 209);
INSERT INTO categories VALUES (N'Khác', 209);
INSERT INTO categories VALUES (N'Sữa công thức trên 24 tháng', 209);
INSERT INTO categories VALUES (N'Sữa công thức 0-24 tháng tuổi', 209);
INSERT INTO categories VALUES (N'Máy Ảnh & Máy Quay Phim', null);
INSERT INTO categories VALUES (N'Máy ảnh - Máy quay phim', 225);
INSERT INTO categories VALUES (N'Camera giám sát & Camera hệ thống', 225);
INSERT INTO categories VALUES (N'Thẻ nhớ', 225);
INSERT INTO categories VALUES (N'Ống kính', 225);
INSERT INTO categories VALUES (N'Phụ kiện máy ảnh', 225);
INSERT INTO categories VALUES (N'Máy bay camera & Phụ kiện', 225);
INSERT INTO categories VALUES (N'Túi Ví Nữ', null);
INSERT INTO categories VALUES (N'Ba Lô Nữ', 232);
INSERT INTO categories VALUES (N'Cặp Laptop', 232);
INSERT INTO categories VALUES (N'Ví Dự Tiệc & Ví Cầm Tay', 232);
INSERT INTO categories VALUES (N'Túi Đeo Hông & Túi Đeo Ngực', 232);
INSERT INTO categories VALUES (N'Túi Tote', 232);
INSERT INTO categories VALUES (N'Túi Quai Xách', 232);
INSERT INTO categories VALUES (N'Túi Đeo Chéo & Túi Đeo Vai', 232);
INSERT INTO categories VALUES (N'Ví/Bóp Nữ', 232);
INSERT INTO categories VALUES (N'Phụ Kiện Túi', 232);
INSERT INTO categories VALUES (N'Khác', 232);
INSERT INTO categories VALUES (N'Ô Tô & Xe Máy & Xe Đạp', null);
INSERT INTO categories VALUES (N'Xe đạp, xe điện', 243);
INSERT INTO categories VALUES (N'Mô tô, xe máy', 243);
INSERT INTO categories VALUES (N'Xe Ô tô', 243);
INSERT INTO categories VALUES (N'Mũ bảo hiểm', 243);
INSERT INTO categories VALUES (N'Phụ kiện xe máy', 243);
INSERT INTO categories VALUES (N'Phụ kiện xe đạp', 243);
INSERT INTO categories VALUES (N'Phụ kiện bên trong ô tô', 243);
INSERT INTO categories VALUES (N'Dầu nhớt & dầu nhờn', 243);
INSERT INTO categories VALUES (N'Phụ tùng ô tô', 243);
INSERT INTO categories VALUES (N'Phụ tùng xe máy', 243);
INSERT INTO categories VALUES (N'Phụ kiện bên ngoài ô tô', 243);
INSERT INTO categories VALUES (N'Chăm sóc ô tô', 243);
INSERT INTO categories VALUES (N'Dịch vụ cho xe', 243);
INSERT INTO categories VALUES (N'Giặt Giũ & Chăm Sóc Nhà Cửa', null);
INSERT INTO categories VALUES (N'Giặt giũ & Chăm sóc nhà cửa', 257);
INSERT INTO categories VALUES (N'Giấy vệ sinh, khăn giấy', 257);
INSERT INTO categories VALUES (N'Vệ sinh nhà cửa', 257);
INSERT INTO categories VALUES (N'Vệ sinh bát đĩa', 257);
INSERT INTO categories VALUES (N'Dụng cụ vệ sinh', 257);
INSERT INTO categories VALUES (N'Chất khử mùi, làm thơm', 257);
INSERT INTO categories VALUES (N'Thuốc diệt côn trùng', 257);
INSERT INTO categories VALUES (N'Túi, màng bọc thực phẩm', 257);
INSERT INTO categories VALUES (N'Bao bì, túi đựng rác', 257);
INSERT INTO categories VALUES (N'Thiết Bị Điện Tử', null);
INSERT INTO categories VALUES (N'Thiết bị đeo thông minh', 267);
INSERT INTO categories VALUES (N'Phụ kiện tivi', 267);
INSERT INTO categories VALUES (N'Máy Game Console', 267);
INSERT INTO categories VALUES (N'Phụ kiện Console', 267);
INSERT INTO categories VALUES (N'Đĩa game', 267);
INSERT INTO categories VALUES (N'Linh phụ kiện', 267);
INSERT INTO categories VALUES (N'Tai nghe nhét tai', 267);
INSERT INTO categories VALUES (N'Loa', 267);
INSERT INTO categories VALUES (N'Tivi', 267);
INSERT INTO categories VALUES (N'Tivi Box', 267);
INSERT INTO categories VALUES (N'Headphones', 267);
INSERT INTO categories VALUES (N'Sức Khỏe', null);
INSERT INTO categories VALUES (N'Vật tư y tế', 279);
INSERT INTO categories VALUES (N'Chống muỗi & xua đuổi côn trùng', 279);
INSERT INTO categories VALUES (N'Thực phẩm chức năng', 279);
INSERT INTO categories VALUES (N'Tã người lớn', 279);
INSERT INTO categories VALUES (N'Hỗ trợ làm đẹp', 279);
INSERT INTO categories VALUES (N'Hỗ trợ tình dục', 279);
INSERT INTO categories VALUES (N'Dụng cụ massage và trị liệu', 279);
INSERT INTO categories VALUES (N'Khác', 279);
INSERT INTO categories VALUES (N'Thiết Bị Điện Gia Dụng', null);
INSERT INTO categories VALUES (N'Đồ gia dụng nhà bếp', 288);
INSERT INTO categories VALUES (N'Đồ gia dụng lớn', 288);
INSERT INTO categories VALUES (N'Máy hút bụi & Thiết bị làm sạch', 288);
INSERT INTO categories VALUES (N'Quạt & Máy nóng lạnh', 288);
INSERT INTO categories VALUES (N'Thiết bị chăm sóc quần áo', 288);
INSERT INTO categories VALUES (N'Khác', 288);
INSERT INTO categories VALUES (N'Máy xay, ép, máy đánh trứng trộn bột, máy xay thực phẩm', 288);
INSERT INTO categories VALUES (N'Bếp điện', 288);
INSERT INTO categories VALUES (N'Nhà Sách Online', null);
INSERT INTO categories VALUES (N'Sách Tiếng Việt', 297);
INSERT INTO categories VALUES (N'Sách ngoại văn', 297);
INSERT INTO categories VALUES (N'Gói Quà', 297);
INSERT INTO categories VALUES (N'Bút viết', 297);
INSERT INTO categories VALUES (N'Dụng cụ học sinh & văn phòng', 297);
INSERT INTO categories VALUES (N'Màu, Họa Cụ và Đồ Thủ Công', 297);
INSERT INTO categories VALUES (N'Sổ và Giấy Các Loại', 297);
INSERT INTO categories VALUES (N'Quà Lưu Niệm', 297);
INSERT INTO categories VALUES (N'Nhạc cụ và phụ kiện âm nhạc', 297);
INSERT INTO categories VALUES (N'Chăm Sóc Thú Cưng', null);
INSERT INTO categories VALUES (N'Thức ăn cho thú cưng', 307);
INSERT INTO categories VALUES (N'Phụ kiện cho thú cưng', 307);
INSERT INTO categories VALUES (N'Vệ sinh cho thú cưng', 307);
INSERT INTO categories VALUES (N'Quần áo thú cưng', 307);
INSERT INTO categories VALUES (N'Chăm sóc sức khỏe', 307);
INSERT INTO categories VALUES (N'Làm đẹp cho thú cưng', 307);
INSERT INTO categories VALUES (N'Khác', 307);
